/-
Copyright (c) 2026 lean-wang contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.5
-/
import LeanWang.OllingerRobinson104RedCycleScaling

/-!
Unbounded red boards generated by the corrected Ollinger substitution.
-/

namespace LeanWang
namespace OllingerRobinson
namespace Figure13Layers
namespace Closed104
namespace RedCycles

theorem betweenAll_eq_true_iff {lower upper : Nat} {predicate : Nat → Bool} :
    betweenAll lower upper predicate = true ↔
      ∀ coordinate, lower < coordinate → coordinate < upper →
        predicate coordinate = true := by
  constructor
  · intro hall coordinate hlower hupper
    have hoffset : coordinate - lower - 1 < upper - lower - 1 := by omega
    have hmember : coordinate - lower - 1 ∈
        List.range (upper - lower - 1) := by
      exact List.mem_range.2 hoffset
    have hpredicate := List.all_eq_true.1 hall
      (coordinate - lower - 1) hmember
    have hcoordinate : lower + 1 + (coordinate - lower - 1) = coordinate := by
      omega
    rw [hcoordinate] at hpredicate
    exact hpredicate
  · intro hpredicate
    apply List.all_eq_true.2
    intro offset hoffset
    have hoffset' : offset < upper - lower - 1 := List.mem_range.1 hoffset
    exact hpredicate (lower + 1 + offset) (by omega) (by omega)

theorem redCycleOn_of_redCycle_eq_true
    {grid : Grid} {west east south north : Nat}
    (hwest : west < east) (hsouth : south < north)
    (hcycle : redCycle grid west east south north = true) :
    RedCycleOn (fun x y => gridAt grid x y) west east south north := by
  simp only [redCycle, Bool.and_eq_true, beq_iff_eq] at hcycle
  refine {
    west_lt_east := hwest
    south_lt_north := hsouth
    southwest := by rw [indexThick_eq]; exact hcycle.1.1.1.1.1
    southeast := by rw [indexThick_eq]; exact hcycle.1.1.1.1.2
    northwest := by rw [indexThick_eq]; exact hcycle.1.1.1.2
    northeast := by rw [indexThick_eq]; exact hcycle.1.1.2
    horizontal := ?_
    vertical := ?_
  }
  · intro x hxWest hxEast
    simpa only [indexThick_eq, thickAt, Bool.and_eq_true] using
      (betweenAll_eq_true_iff.1 hcycle.1.2 x hxWest hxEast)
  · intro y hySouth hyNorth
    simpa only [indexThick_eq, thickAt, Bool.and_eq_true] using
      (betweenAll_eq_true_iff.1 hcycle.2 y hySouth hyNorth)


theorem depthTwo_supertile_has_fixed_redCycleOn (parent : Index) :
    RedCycleOn (fun x y => gridAt (supertile 2 parent) x y) 1 3 1 3 :=
  redCycleOn_of_redCycle_eq_true (by decide) (by decide)
    (depthTwo_supertile_has_fixed_redCycle parent)

/-- Iterate simultaneous Figure 16 substitution on an index grid. -/
def iterateRefine : Nat → (Nat → Nat → Index) → Nat → Nat → Index
  | 0, grid => grid
  | level + 1, grid => refineIndexGrid (iterateRefine level grid)

/-- Multiply a coordinate by two once per refinement. -/
def doubleN : Nat → Nat → Nat
  | 0, coordinate => coordinate
  | level + 1, coordinate => 2 * doubleN level coordinate

@[simp]
theorem doubleN_eq (level coordinate : Nat) :
    doubleN level coordinate = 2 ^ level * coordinate := by
  induction level with
  | zero => simp [doubleN]
  | succ level ih =>
      rw [doubleN, ih, pow_succ]
      ac_rfl

/-- A red cycle remains a red cycle through arbitrarily many refinements. -/
theorem RedCycleOn.iterateRefine {grid : Nat → Nat → Index}
    {west east south north : Nat}
    (cycle : RedCycleOn grid west east south north) (level : Nat) :
    RedCycleOn (RedCycles.iterateRefine level grid)
      (doubleN level west) (doubleN level east)
      (doubleN level south) (doubleN level north) := by
  induction level with
  | zero =>
      change RedCycleOn grid west east south north
      exact cycle
  | succ level ih =>
      change RedCycleOn
        (refineIndexGrid (RedCycles.iterateRefine level grid))
        (2 * doubleN level west) (2 * doubleN level east)
        (2 * doubleN level south) (2 * doubleN level north)
      exact ih.refine


end RedCycles
end Closed104
end Figure13Layers
end OllingerRobinson
end LeanWang
