/-
Copyright (c) 2026 lean-wang contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.5
-/
import LeanWang.RoutedPointedPlane

/-!
# Logical labels from pointed full-plane payloads

A concrete routed scaffold labels active crossings by integer coordinates in a
pointed payload plane.  Channel labels name individual edges at those logical
coordinates.  The symbolic compatibility relation then discharges all payload
matching and palette obligations independently of the concrete scaffold.
-/

namespace LeanWang
namespace RoutedPointedCoreLabeling

/-- A pointed payload plane packaged for logical label interpretation. -/
structure PlaneData (T : TileSet) (seed : WangTile) where
  tile : Int × Int → TileIn T
  valid : ValidPlaneTiling T tile
  pointed : (tile (0, 0)).1 = seed

/-- Symbolic source of one edge color in a pointed payload plane. -/
inductive EdgeLabel where
  | zero
  | north (point : Int × Int)
  | south (point : Int × Int)
  | east (point : Int × Int)
  | west (point : Int × Int)
deriving DecidableEq, Repr

namespace EdgeLabel

def color {T : TileSet} {seed : WangTile}
    (plane : PlaneData T seed) : EdgeLabel → Nat
  | .zero => 0
  | .north point => (plane.tile point).1.n
  | .south point => (plane.tile point).1.s
  | .east point => (plane.tile point).1.e
  | .west point => (plane.tile point).1.w

theorem color_mem_payloadPalette
    {T : TileSet} {seed : WangTile}
    (plane : PlaneData T seed) (edge : EdgeLabel) :
    edge.color plane ∈ payloadPalette T := by
  cases edge with
  | zero => exact zero_mem_payloadPalette T
  | north point => exact mem_payloadPalette_n (plane.tile point).2
  | south point => exact mem_payloadPalette_s (plane.tile point).2
  | east point => exact mem_payloadPalette_e (plane.tile point).2
  | west point => exact mem_payloadPalette_w (plane.tile point).2

/-- Symbolic equality generated by literal identity and the two payload-plane
adjacencies. -/
inductive Compatible : EdgeLabel → EdgeLabel → Prop where
  | refl (edge : EdgeLabel) : Compatible edge edge
  | horizontal (point : Int × Int) :
      Compatible (.east point) (.west (point.1 + 1, point.2))
  | vertical (point : Int × Int) :
      Compatible (.north point) (.south (point.1, point.2 + 1))

theorem Compatible.color_eq
    {T : TileSet} {seed : WangTile}
    (plane : PlaneData T seed)
    {first second : EdgeLabel} (compatible : Compatible first second) :
    first.color plane = second.color plane := by
  cases compatible with
  | refl => rfl
  | horizontal point => exact plane.valid.1 point
  | vertical point => exact plane.valid.2 point

end EdgeLabel

/-- Logical meaning of one constrained physical scaffold cell. -/
inductive Label where
  | inactive
  | tile (point : Int × Int)
  | channel (north south east west : EdgeLabel)
deriving Repr

namespace Label

def payload {T : TileSet} {seed : WangTile}
    (plane : PlaneData T seed) : Label → WangTile
  | .inactive => { n := 0, s := 0, e := 0, w := 0 }
  | .tile point => (plane.tile point).1
  | .channel north south east west =>
      { n := north.color plane, s := south.color plane,
        e := east.color plane, w := west.color plane }

def north : Label → EdgeLabel
  | .inactive => .zero
  | .tile point => .north point
  | .channel north _ _ _ => north

def south : Label → EdgeLabel
  | .inactive => .zero
  | .tile point => .south point
  | .channel _ south _ _ => south

def east : Label → EdgeLabel
  | .inactive => .zero
  | .tile point => .east point
  | .channel _ _ east _ => east

def west : Label → EdgeLabel
  | .inactive => .zero
  | .tile point => .west point
  | .channel _ _ _ west => west

@[simp] theorem payload_north
    {T : TileSet} {seed : WangTile}
    (plane : PlaneData T seed) (label : Label) :
    (payload plane label).n = label.north.color plane := by
  cases label <;> rfl

@[simp] theorem payload_south
    {T : TileSet} {seed : WangTile}
    (plane : PlaneData T seed) (label : Label) :
    (payload plane label).s = label.south.color plane := by
  cases label <;> rfl

@[simp] theorem payload_east
    {T : TileSet} {seed : WangTile}
    (plane : PlaneData T seed) (label : Label) :
    (payload plane label).e = label.east.color plane := by
  cases label <;> rfl

@[simp] theorem payload_west
    {T : TileSet} {seed : WangTile}
    (plane : PlaneData T seed) (label : Label) :
    (payload plane label).w = label.west.color plane := by
  cases label <;> rfl

def FitsRole : Label → RouteRole → Prop
  | .inactive, .inactive => True
  | .tile _, .active => True
  | .tile point, .corner => point = (0, 0)
  | .channel _ _ east west, .horizontal => west = east
  | .channel north south _ _, .vertical => south = north
  | _, _ => False

def HCompatible (first second : Label) : Prop :=
  EdgeLabel.Compatible first.east second.west

def VCompatible (lower upper : Label) : Prop :=
  EdgeLabel.Compatible lower.north upper.south

theorem payload_hmatch
    {T : TileSet} {seed : WangTile}
    (plane : PlaneData T seed) {first second : Label}
    (compatible : HCompatible first second) :
    WangTile.HMatches (payload plane first) (payload plane second) := by
  simpa only [WangTile.HMatches, payload_east, payload_west] using
    compatible.color_eq plane

theorem payload_vmatch
    {T : TileSet} {seed : WangTile}
    (plane : PlaneData T seed) {lower upper : Label}
    (compatible : VCompatible lower upper) :
    WangTile.VMatches (payload plane lower) (payload plane upper) := by
  simpa only [WangTile.VMatches, payload_north, payload_south] using
    compatible.color_eq plane

theorem payload_mem_routedPayloads
    {S : RoutedScaffold} {T : TileSet} {seed base : WangTile}
    (plane : PlaneData T seed) {label : Label}
    (fits : FitsRole label (S.role base)) :
    payload plane label ∈ routedPayloads S T seed base := by
  rw [mem_routedPayloads_iff]
  cases roleEq : S.role base with
  | inactive =>
      simp only [roleEq] at fits ⊢
      cases label with
      | inactive =>
          exact mk_mem_completePayloads
            (zero_mem_payloadPalette T) (zero_mem_payloadPalette T)
            (zero_mem_payloadPalette T) (zero_mem_payloadPalette T)
      | tile => simp [FitsRole] at fits
      | channel => simp [FitsRole] at fits
  | horizontal =>
      simp only [roleEq] at fits ⊢
      cases label with
      | inactive => simp [FitsRole] at fits
      | tile => simp [FitsRole] at fits
      | channel north south east west =>
          refine ⟨?_, ?_⟩
          · exact mk_mem_completePayloads
              (north.color_mem_payloadPalette plane)
              (south.color_mem_payloadPalette plane)
              (east.color_mem_payloadPalette plane)
              (west.color_mem_payloadPalette plane)
          · simpa [payload] using congrArg (EdgeLabel.color plane) fits
  | vertical =>
      simp only [roleEq] at fits ⊢
      cases label with
      | inactive => simp [FitsRole] at fits
      | tile => simp [FitsRole] at fits
      | channel north south east west =>
          refine ⟨?_, ?_⟩
          · exact mk_mem_completePayloads
              (north.color_mem_payloadPalette plane)
              (south.color_mem_payloadPalette plane)
              (east.color_mem_payloadPalette plane)
              (west.color_mem_payloadPalette plane)
          · simpa [payload] using congrArg (EdgeLabel.color plane) fits
  | active =>
      simp only [roleEq] at fits ⊢
      cases label with
      | inactive => simp [FitsRole] at fits
      | tile point => exact (plane.tile point).2
      | channel => simp [FitsRole] at fits
  | corner =>
      simp only [roleEq] at fits ⊢
      cases label with
      | inactive => simp [FitsRole] at fits
      | tile point =>
          simp only [FitsRole] at fits
          subst point
          exact ⟨(plane.tile (0, 0)).2, plane.pointed⟩
      | channel => simp [FitsRole] at fits

end Label

/-- A finite scaffold box labeled by coordinates in any pointed payload
plane. -/
structure Labeling (S : RoutedScaffold) (r : Nat) where
  base : BoxPattern S.tiles r
  label : Box r → Label
  base_valid : ValidBoxTiling S.tiles r base
  fits : ∀ point : Box r,
    (label point).FitsRole (S.role (base point).1)
  hcompatible :
    ∀ point : Box r, ∀ next : InBox r (point.1.1 + 1, point.1.2),
      (S.role (base point).1).isConstrained = true →
      (S.role (base ⟨(point.1.1 + 1, point.1.2), next⟩).1).isConstrained = true →
      Label.HCompatible (label point)
        (label ⟨(point.1.1 + 1, point.1.2), next⟩)
  vcompatible :
    ∀ point : Box r, ∀ next : InBox r (point.1.1, point.1.2 + 1),
      (S.role (base point).1).isConstrained = true →
      (S.role (base ⟨(point.1.1, point.1.2 + 1), next⟩).1).isConstrained = true →
      Label.VCompatible (label point)
        (label ⟨(point.1.1, point.1.2 + 1), next⟩)

def Labeling.toRoutedCoreBoxLayerPatch
    {S : RoutedScaffold} {T : TileSet} {seed : WangTile} {r : Nat}
    (labeling : Labeling S r) (plane : PlaneData T seed) :
    RoutedCoreBoxLayerPatch S T seed r where
  base := labeling.base
  core := fun point => (labeling.label point).payload plane
  base_valid := labeling.base_valid
  core_mem := fun point =>
    Label.payload_mem_routedPayloads plane (labeling.fits point)
  core_hmatch := by
    intro point next left right
    exact Label.payload_hmatch plane
      (labeling.hcompatible point next left right)
  core_vmatch := by
    intro point next lower upper
    exact Label.payload_vmatch plane
      (labeling.vcompatible point next lower upper)

/-- Pure scaffold geometry sufficient to route every pointed payload plane. -/
def HasRoutedPointedCoreLabelings (S : RoutedScaffold) : Prop :=
  ∀ r : Nat, Nonempty (Labeling S r)

theorem hasRoutedCoreBoxLayerPatchesOfPointedPlanes_of_labelings
    {S : RoutedScaffold} (labelings : HasRoutedPointedCoreLabelings S) :
    HasRoutedCoreBoxLayerPatchesOfPointedPlanes S := by
  intro T seed tile valid pointed radius
  rcases labelings radius with ⟨labeling⟩
  let plane : PlaneData T seed := ⟨tile, valid, pointed⟩
  exact ⟨labeling.toRoutedCoreBoxLayerPatch plane⟩

theorem realizesRoutedPointedPlanes_of_labelings
    {S : RoutedScaffold} (labelings : HasRoutedPointedCoreLabelings S) :
    RealizesRoutedPointedPlanes S :=
  realizesRoutedPointedPlanes_of_combinedBoxLayerPatches
    (hasRoutedCombinedBoxLayerPatchesOfPointedPlanes_of_core
      (hasRoutedCoreBoxLayerPatchesOfPointedPlanes_of_labelings labelings))

end RoutedPointedCoreLabeling
end LeanWang
