/-
Copyright (c) 2026 lean-wang contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.5
-/
import LeanWang.TM0FoldedCompiler.Correctness
import LeanWang.TM0FoldedGeneratedInit

/-!
Local simulation and reachability lemmas for the generated position-coded
folded program.

`TM0FoldedCompiler` proves correctness for the canonical folded program.  This
file reuses the same folded-configuration invariant for `positionProgramData`,
whose rows are generated by executable position-coded decoders.  The key local
difference is that simulation-row lookups go through
`positionProgramData_step_sim_of_step`, so no global equality with the canonical
row list is needed.
-/

noncomputable section

namespace LeanWang

namespace TM0FoldedCompiler

set_option linter.flexible false in
theorem FoldedConfigRel_position_write_step
    {tc : Turing.ToPartrec.Code}
    {cfg : Turing.TM0.Cfg SourceSymbol (SourceLabel tc)} {id : PostID}
    {q' : SourceLabel tc} {new : SourceSymbol}
    (hrel : FoldedConfigRel tc cfg id)
    (hstep :
      TM0Route.partrecStartedTM0Machine tc cfg.q cfg.Tape.head =
        some (q', Turing.TM0.Stmt.write new)) :
    FoldedConfigRel tc
      { q := q', Tape := cfg.Tape.write new }
      ((positionProgramData tc).nextID id) := by
  rcases hrel with ⟨side, hq, hstate, htape⟩
  let left := cfg.Tape.nth (sourceOffset side id.head (leftAbs id.head))
  let right := cfg.Tape.nth (sourceOffset side id.head (rightAbs id.head))
  have hread :
      foldedRead side left right = cfg.Tape.head := by
    unfold left right
    exact foldedRead_active_cell cfg.Tape side id.head
  have hstep' :
      TM0Route.partrecStartedTM0Machine tc cfg.q (foldedRead side left right) =
        some (q', Turing.TM0.Stmt.write new) := by
    simpa [hread] using hstep
  have hcell :
      id.tape id.head = foldedSymbolCode (decide (id.head = 0)) left right := by
    rw [htape id.head]
    simp [foldedCellOfTapeAt, left, right]
  have hprogramStep := positionProgramData_step_sim_of_step
    (tc := tc) (q := cfg.q) (q' := q') (side := side)
    (marked := decide (id.head = 0)) (left := left) (right := right)
    (stmt := Turing.TM0.Stmt.write new) hq hstep'
  simp [PostProgram.nextID, hstate, hcell, hprogramStep, PostProgram.applyStmt,
    simRowOfStep, left, right]
  refine ⟨side, ?_, rfl, ?_⟩
  · have hqset : cfg.q ∈ TM0Route.partrecStartedTM0Labels tc :=
      (TM0Route.mem_partrecStartedTM0LabelList tc cfg.q).1 hq
    have hq'set : q' ∈ TM0Route.partrecStartedTM0Labels tc :=
      TM0FiniteCompiler.next_label_mem_of_step hqset hstep
    exact (TM0Route.mem_partrecStartedTM0LabelList tc q').2 hq'set
  · exact FoldedTapeRel_write new htape

set_option linter.flexible false in
theorem FoldedConfigRel_position_move_step
    {tc : Turing.ToPartrec.Code}
    {cfg : Turing.TM0.Cfg SourceSymbol (SourceLabel tc)} {id : PostID}
    {q' : SourceLabel tc} {dir : Turing.Dir}
    (hrel : FoldedConfigRel tc cfg id)
    (hstep :
      TM0Route.partrecStartedTM0Machine tc cfg.q cfg.Tape.head =
        some (q', Turing.TM0.Stmt.move dir)) :
    FoldedConfigRel tc
      { q := q', Tape := cfg.Tape.move dir }
      ((positionProgramData tc).nextID id) := by
  rcases hrel with ⟨side, hq, hstate, htape⟩
  let marked := decide (id.head = 0)
  let left := cfg.Tape.nth (sourceOffset side id.head (leftAbs id.head))
  let right := cfg.Tape.nth (sourceOffset side id.head (rightAbs id.head))
  let read := foldedSymbolCode marked left right
  have hread :
      foldedRead side left right = cfg.Tape.head := by
    unfold left right
    exact foldedRead_active_cell cfg.Tape side id.head
  have hstep' :
      TM0Route.partrecStartedTM0Machine tc cfg.q (foldedRead side left right) =
        some (q', Turing.TM0.Stmt.move dir) := by
    simpa [hread] using hstep
  have hcell : id.tape id.head = read := by
    rw [htape id.head]
    simp [foldedCellOfTapeAt, marked, left, right, read]
  have hprogramStep := positionProgramData_step_sim_of_step
    (tc := tc) (q := cfg.q) (q' := q') (side := side)
    (marked := marked) (left := left) (right := right)
    (stmt := Turing.TM0.Stmt.move dir) hq hstep'
  have hq'list : q' ∈ TM0Route.partrecStartedTM0LabelList tc := by
    have hqset : cfg.q ∈ TM0Route.partrecStartedTM0Labels tc :=
      (TM0Route.mem_partrecStartedTM0LabelList tc cfg.q).1 hq
    have hq'set : q' ∈ TM0Route.partrecStartedTM0Labels tc :=
      TM0FiniteCompiler.next_label_mem_of_step hqset hstep
    exact (TM0Route.mem_partrecStartedTM0LabelList tc q').2 hq'set
  have htapeApply :
      (PostProgram.applyStmt (foldedMoveStmt side marked read dir) id.tape id.head).1 =
        id.tape := by
    exact foldedMoveStmt_applyStmt_tape side marked read dir hcell
  have hheadApply :
      (PostProgram.applyStmt (foldedMoveStmt side marked read dir) id.tape id.head).2 =
        foldedMoveHead side marked id.head dir := by
    exact foldedMoveStmt_applyStmt_head side marked read dir id.tape id.head
  simp [PostProgram.nextID, hstate, hcell, hprogramStep, simRowOfStep, marked, read]
  refine ⟨foldedMoveNextSide side marked dir, hq'list, ?_, ?_⟩
  · simp [mkRow, marked]
  · simpa [mkRow, marked, read, htapeApply, hheadApply]
      using FoldedTapeRel_move (T := cfg.Tape) (side := side)
      (head := id.head) (tape := id.tape) dir htape

theorem FoldedConfigRel_position_step
    {tc : Turing.ToPartrec.Code}
    {cfg cfg' : Turing.TM0.Cfg SourceSymbol (SourceLabel tc)} {id : PostID}
    (hrel : FoldedConfigRel tc cfg id)
    (hstep :
      Turing.TM0.step (TM0Route.partrecStartedTM0Machine tc) cfg = some cfg') :
    FoldedConfigRel tc cfg' ((positionProgramData tc).nextID id) := by
  cases hM :
      TM0Route.partrecStartedTM0Machine tc cfg.q cfg.Tape.head with
  | none =>
      simp [Turing.TM0.step, hM] at hstep
  | some next =>
      rcases next with ⟨q', stmt⟩
      cases stmt with
      | move dir =>
          have hcfg' : cfg' = { q := q', Tape := cfg.Tape.move dir } := by
            simpa [Turing.TM0.step, hM] using hstep.symm
          subst cfg'
          exact FoldedConfigRel_position_move_step (tc := tc) (cfg := cfg) (id := id)
            (q' := q') (dir := dir) hrel hM
      | write new =>
          have hcfg' : cfg' = { q := q', Tape := cfg.Tape.write new } := by
            simpa [Turing.TM0.step, hM] using hstep.symm
          subst cfg'
          exact FoldedConfigRel_position_write_step (tc := tc) (cfg := cfg) (id := id)
            (q' := q') (new := new) hrel hM

theorem FoldedConfigRel_position_halt_step
    {tc : Turing.ToPartrec.Code}
    {cfg : Turing.TM0.Cfg SourceSymbol (SourceLabel tc)} {id : PostID}
    (hrel : FoldedConfigRel tc cfg id)
    (hstep :
      Turing.TM0.step (TM0Route.partrecStartedTM0Machine tc) cfg = none) :
    ((positionProgramData tc).nextID id).state = none := by
  rcases hrel with ⟨side, hq, hstate, htape⟩
  let marked := decide (id.head = 0)
  let left := cfg.Tape.nth (sourceOffset side id.head (leftAbs id.head))
  let right := cfg.Tape.nth (sourceOffset side id.head (rightAbs id.head))
  let read := foldedSymbolCode marked left right
  have hread :
      foldedRead side left right = cfg.Tape.head := by
    unfold left right
    exact foldedRead_active_cell cfg.Tape side id.head
  have hmachine :
      TM0Route.partrecStartedTM0Machine tc cfg.q cfg.Tape.head = none := by
    cases hM : TM0Route.partrecStartedTM0Machine tc cfg.q cfg.Tape.head with
    | none => simp
    | some next =>
        simp [Turing.TM0.step, hM] at hstep
  have hmachine' :
      TM0Route.partrecStartedTM0Machine tc cfg.q (foldedRead side left right) =
        none := by
    simpa [hread] using hmachine
  have hcell : id.tape id.head = read := by
    rw [htape id.head]
    simp [foldedCellOfTapeAt, marked, left, right, read]
  have hprogramStep := positionProgramData_step_sim_eq_none_of_no_step
    (tc := tc) (q := cfg.q) (side := side) (marked := marked)
    (left := left) (right := right) hq hmachine'
  simp [PostProgram.nextID, hstate, hcell, hprogramStep, read]

theorem FoldedConfigRel_position_reaches
    {tc : Turing.ToPartrec.Code}
    {cfg cfg' : Turing.TM0.Cfg SourceSymbol (SourceLabel tc)} {id : PostID}
    (hrel : FoldedConfigRel tc cfg id)
    (hreach :
      StateTransition.Reaches
        (Turing.TM0.step (TM0Route.partrecStartedTM0Machine tc)) cfg cfg') :
    ∃ n : Nat,
      FoldedConfigRel tc cfg' (Nat.iterate (positionProgramData tc).nextID n id) := by
  induction hreach with
  | refl =>
      exact ⟨0, hrel⟩
  | tail _ hstep ih =>
      rcases ih with ⟨n, hn⟩
      refine ⟨n + 1, ?_⟩
      rw [Function.iterate_succ_apply']
      exact FoldedConfigRel_position_step hn (by simpa using hstep)

theorem FoldedConfigRel_position_reaches_halt
    {tc : Turing.ToPartrec.Code}
    {cfg cfg' : Turing.TM0.Cfg SourceSymbol (SourceLabel tc)} {id : PostID}
    (hrel : FoldedConfigRel tc cfg id)
    (hreach :
      StateTransition.Reaches
        (Turing.TM0.step (TM0Route.partrecStartedTM0Machine tc)) cfg cfg')
    (hhalt :
      Turing.TM0.step (TM0Route.partrecStartedTM0Machine tc) cfg' = none) :
    ∃ n : Nat, (Nat.iterate (positionProgramData tc).nextID n id).state = none := by
  rcases FoldedConfigRel_position_reaches (tc := tc) hrel hreach with ⟨n, hn⟩
  refine ⟨n + 1, ?_⟩
  rw [Function.iterate_succ_apply']
  exact FoldedConfigRel_position_halt_step hn hhalt

theorem FoldedConfigRel_position_runEmpty_two (tc : Turing.ToPartrec.Code) :
    FoldedConfigRel tc
      (Turing.TM0.init (Λ := SourceLabel tc) TM0Route.partrecStartedTM0Input)
      ((positionProgramData tc).runEmpty 2) := by
  rw [positionProgramData_runEmpty_two]
  refine ⟨FoldSide.right, ?_, ?_, ?_⟩
  · simpa [Turing.TM0.init] using default_mem_partrecStartedTM0LabelList tc
  · simp [foldedSimStartState, foldedSimStartStateCode, foldedSimStateCode,
      foldedSimStateOfCode, TM0Route.partrecStartedTM0Start,
      TM0FiniteCompiler.stateCode_default tc, Turing.TM0.init]
  · exact FoldedTapeRel_init_right_zero tc

end TM0FoldedCompiler

end LeanWang
