/-
Copyright (c) 2026 lean-wang contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.5
-/
import LeanWang.TM0FoldedCompiler.Correctness

/-!
Local write and move simulation lemmas for the generated position-coded folded
program.

`TM0FoldedCompiler` proves correctness for the canonical folded program.  This
file reuses the same folded-configuration invariant for `positionProgramData`,
whose rows are generated by executable position-coded decoders.  The key local
difference is that simulation-row lookups go through
`positionProgramData_step_sim_of_step`, so no global equality with the canonical
row list is needed.
-/

noncomputable section

namespace LeanWang

namespace TM0FoldedCompiler

set_option linter.flexible false in
theorem FoldedConfigRel_position_write_step
    {tc : Turing.ToPartrec.Code}
    {cfg : Turing.TM0.Cfg SourceSymbol (SourceLabel tc)} {id : PostID}
    {q' : SourceLabel tc} {new : SourceSymbol}
    (hrel : FoldedConfigRel tc cfg id)
    (hstep :
      TM0Route.partrecStartedTM0Machine tc cfg.q cfg.Tape.head =
        some (q', Turing.TM0.Stmt.write new)) :
    FoldedConfigRel tc
      { q := q', Tape := cfg.Tape.write new }
      ((positionProgramData tc).nextID id) := by
  rcases hrel with ⟨side, hq, hstate, htape⟩
  let left := cfg.Tape.nth (sourceOffset side id.head (leftAbs id.head))
  let right := cfg.Tape.nth (sourceOffset side id.head (rightAbs id.head))
  have hread :
      foldedRead side left right = cfg.Tape.head := by
    unfold left right
    exact foldedRead_active_cell cfg.Tape side id.head
  have hstep' :
      TM0Route.partrecStartedTM0Machine tc cfg.q (foldedRead side left right) =
        some (q', Turing.TM0.Stmt.write new) := by
    simpa [hread] using hstep
  have hcell :
      id.tape id.head = foldedSymbolCode (decide (id.head = 0)) left right := by
    rw [htape id.head]
    simp [foldedCellOfTapeAt, left, right]
  have hprogramStep := positionProgramData_step_sim_of_step
    (tc := tc) (q := cfg.q) (q' := q') (side := side)
    (marked := decide (id.head = 0)) (left := left) (right := right)
    (stmt := Turing.TM0.Stmt.write new) hq hstep'
  simp [PostProgram.nextID, hstate, hcell, hprogramStep, PostProgram.applyStmt,
    simRowOfStep, left, right]
  refine ⟨side, ?_, rfl, ?_⟩
  · have hqset : cfg.q ∈ TM0Route.partrecStartedTM0Labels tc :=
      (TM0Route.mem_partrecStartedTM0LabelList tc cfg.q).1 hq
    have hq'set : q' ∈ TM0Route.partrecStartedTM0Labels tc :=
      TM0FiniteCompiler.next_label_mem_of_step hqset hstep
    exact (TM0Route.mem_partrecStartedTM0LabelList tc q').2 hq'set
  · exact FoldedTapeRel_write new htape

set_option linter.flexible false in
theorem FoldedConfigRel_position_move_step
    {tc : Turing.ToPartrec.Code}
    {cfg : Turing.TM0.Cfg SourceSymbol (SourceLabel tc)} {id : PostID}
    {q' : SourceLabel tc} {dir : Turing.Dir}
    (hrel : FoldedConfigRel tc cfg id)
    (hstep :
      TM0Route.partrecStartedTM0Machine tc cfg.q cfg.Tape.head =
        some (q', Turing.TM0.Stmt.move dir)) :
    FoldedConfigRel tc
      { q := q', Tape := cfg.Tape.move dir }
      ((positionProgramData tc).nextID id) := by
  rcases hrel with ⟨side, hq, hstate, htape⟩
  let marked := decide (id.head = 0)
  let left := cfg.Tape.nth (sourceOffset side id.head (leftAbs id.head))
  let right := cfg.Tape.nth (sourceOffset side id.head (rightAbs id.head))
  let read := foldedSymbolCode marked left right
  have hread :
      foldedRead side left right = cfg.Tape.head := by
    unfold left right
    exact foldedRead_active_cell cfg.Tape side id.head
  have hstep' :
      TM0Route.partrecStartedTM0Machine tc cfg.q (foldedRead side left right) =
        some (q', Turing.TM0.Stmt.move dir) := by
    simpa [hread] using hstep
  have hcell : id.tape id.head = read := by
    rw [htape id.head]
    simp [foldedCellOfTapeAt, marked, left, right, read]
  have hprogramStep := positionProgramData_step_sim_of_step
    (tc := tc) (q := cfg.q) (q' := q') (side := side)
    (marked := marked) (left := left) (right := right)
    (stmt := Turing.TM0.Stmt.move dir) hq hstep'
  have hq'list : q' ∈ TM0Route.partrecStartedTM0LabelList tc := by
    have hqset : cfg.q ∈ TM0Route.partrecStartedTM0Labels tc :=
      (TM0Route.mem_partrecStartedTM0LabelList tc cfg.q).1 hq
    have hq'set : q' ∈ TM0Route.partrecStartedTM0Labels tc :=
      TM0FiniteCompiler.next_label_mem_of_step hqset hstep
    exact (TM0Route.mem_partrecStartedTM0LabelList tc q').2 hq'set
  have htapeApply :
      (PostProgram.applyStmt (foldedMoveStmt side marked read dir) id.tape id.head).1 =
        id.tape := by
    exact foldedMoveStmt_applyStmt_tape side marked read dir hcell
  have hheadApply :
      (PostProgram.applyStmt (foldedMoveStmt side marked read dir) id.tape id.head).2 =
        foldedMoveHead side marked id.head dir := by
    exact foldedMoveStmt_applyStmt_head side marked read dir id.tape id.head
  simp [PostProgram.nextID, hstate, hcell, hprogramStep, simRowOfStep, marked, read]
  refine ⟨foldedMoveNextSide side marked dir, hq'list, ?_, ?_⟩
  · simp [mkRow, marked]
  · simpa [mkRow, marked, read, htapeApply, hheadApply]
      using FoldedTapeRel_move (T := cfg.Tape) (side := side)
      (head := id.head) (tape := id.tape) dir htape

end TM0FoldedCompiler

end LeanWang
