/-
Copyright (c) 2026 lean-wang contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.6
-/
import LeanWang.Kari.Hooper.CounterControlPlan

/-!
# Well-formedness of the oriented counter-control plan

This file proves the finite indexing facts that connect the symbolic search
addresses in `CounterControlPlan` to the uniform command blocks generated by
`BoundedMarkerProgram`.
-/

namespace LeanWang
namespace Kari
namespace Hooper
namespace CounterControlWellFormed

open Turing CounterMachine
open BoundedMarkerProgram CounterControlPlan

noncomputable section

/-! ## Closed symbolic address layout -/

private def address (growth : Turing.Dir) (source slot : Nat) :
    SearchAddress :=
  ⟨growth, source, slot⟩

/-- The validation sweep owns the first eight search slots. -/
def validationAddresses (growth : Turing.Dir) (source : Nat) :
    List SearchAddress :=
  [ address growth source 0
  , address growth source 1
  , address growth source 2
  , address growth source 3
  , address growth source 4
  , address growth source 5
  , address growth source 6
  , address growth source 7
  ]

/-- Search addresses used by an increment, including its collision cleanup. -/
def incrementAddresses (growth : Turing.Dir) (source : Nat) :
    Register → List SearchAddress
  | .left =>
      [ address growth source 16, address growth source 17
      , address growth source 18, address growth source 19
      , address growth source 24, address growth source 25
      , address growth source 26
      , address growth source 40, address growth source 41
      , address growth source 42, address growth source 43
      , address growth source 44 ]
  | .right =>
      [ address growth source 16, address growth source 17
      , address growth source 18
      , address growth source 24, address growth source 25
      , address growth source 40, address growth source 41
      , address growth source 42, address growth source 43
      , address growth source 44 ]
  | .temp =>
      [ address growth source 16, address growth source 17
      , address growth source 24
      , address growth source 40, address growth source 41
      , address growth source 42, address growth source 43
      , address growth source 44 ]
  | .clock =>
      [ address growth source 16
      , address growth source 40, address growth source 41
      , address growth source 42, address growth source 43
      , address growth source 44 ]

/-- Search addresses used by both branches of a conditional decrement. -/
def decrementAddresses (growth : Turing.Dir) (source : Nat) :
    Register → List SearchAddress
  | .left =>
      [ address growth source 16, address growth source 17
      , address growth source 18
      , address growth source 24, address growth source 25
      , address growth source 26, address growth source 27
      , address growth source 32, address growth source 33
      , address growth source 34, address growth source 35 ]
  | .right =>
      [ address growth source 16, address growth source 17
      , address growth source 24, address growth source 25
      , address growth source 26
      , address growth source 32, address growth source 33
      , address growth source 34 ]
  | .temp =>
      [ address growth source 16
      , address growth source 24, address growth source 25
      , address growth source 32, address growth source 33 ]
  | .clock =>
      [ address growth source 24, address growth source 32 ]

/-- Address list generated by one fixed counter rule. -/
def ruleAddresses (growth : Turing.Dir) (rule : CounterMachine.Rule) :
    List SearchAddress :=
  validationAddresses growth rule.1 ++
    match rule.2 with
    | .increment register _ => incrementAddresses growth rule.1 register
    | .decrement register _ _ => decrementAddresses growth rule.1 register

/-- The explicit address layout is definitionally the one emitted by the
controller compiler. -/
theorem rawCommandsFor_addresses (growth : Turing.Dir) :
    (rawCommandsFor growth).map RawCommand.address =
      GlobalSourceProgram.program.flatMap (ruleAddresses growth) := by
  rw [rawCommandsFor, List.map_flatMap]
  apply congrArg (fun f : CounterMachine.Rule → List SearchAddress =>
    GlobalSourceProgram.program.flatMap f)
  funext rule
  rcases rule with ⟨source, instruction⟩
  cases instruction with
  | increment register next => cases register <;> rfl
  | decrement register ifZero ifPositive => cases register <;> rfl

theorem counterState_eq_of_mem_ruleAddresses
    {growth : Turing.Dir} {rule : CounterMachine.Rule}
    {address' : SearchAddress} (haddress : address' ∈ ruleAddresses growth rule) :
    address'.counterState = rule.1 := by
  rcases rule with ⟨source, instruction⟩
  cases instruction with
  | increment register next =>
      cases register <;>
        simp [ruleAddresses, validationAddresses, incrementAddresses,
          address] at haddress <;>
        aesop
  | decrement register ifZero ifPositive =>
      cases register <;>
        simp [ruleAddresses, validationAddresses, decrementAddresses,
          address] at haddress <;>
        aesop

theorem growth_eq_of_mem_ruleAddresses
    {growth : Turing.Dir} {rule : CounterMachine.Rule}
    {address' : SearchAddress} (haddress : address' ∈ ruleAddresses growth rule) :
    address'.growth = growth := by
  rcases rule with ⟨source, instruction⟩
  cases instruction with
  | increment register next =>
      cases register <;>
        simp [ruleAddresses, validationAddresses, incrementAddresses,
          address] at haddress <;>
        aesop
  | decrement register ifZero ifPositive =>
      cases register <;>
        simp [ruleAddresses, validationAddresses, decrementAddresses,
          address] at haddress <;>
        aesop

theorem slot_lt_directStride_of_mem_ruleAddresses
    {growth : Turing.Dir} {rule : CounterMachine.Rule}
    {address' : SearchAddress} (haddress : address' ∈ ruleAddresses growth rule) :
    address'.slot < directStride := by
  rcases rule with ⟨source, instruction⟩
  cases instruction with
  | increment register next =>
      cases register <;>
        simp [ruleAddresses, validationAddresses, incrementAddresses,
          address, directStride] at haddress ⊢ <;>
        aesop
  | decrement register ifZero ifPositive =>
      cases register <;>
        simp [ruleAddresses, validationAddresses, decrementAddresses,
          address, directStride] at haddress ⊢ <;>
        aesop

theorem ruleAddresses_nodup (growth : Turing.Dir)
    (rule : CounterMachine.Rule) :
    (ruleAddresses growth rule).Nodup := by
  rcases rule with ⟨source, instruction⟩
  cases instruction with
  | increment register next =>
      cases register <;>
        simp [ruleAddresses, validationAddresses, incrementAddresses,
          address]
  | decrement register ifZero ifPositive =>
      cases register <;>
        simp [ruleAddresses, validationAddresses, decrementAddresses,
          address]

theorem ruleAddresses_disjoint_of_source_ne (growth : Turing.Dir)
    {first second : CounterMachine.Rule} (hne : first.1 ≠ second.1) :
    List.Disjoint (ruleAddresses growth first)
      (ruleAddresses growth second) := by
  rw [List.disjoint_iff_ne]
  intro firstAddress hfirst secondAddress hsecond heq
  apply hne
  calc
    first.1 = firstAddress.counterState :=
      (counterState_eq_of_mem_ruleAddresses hfirst).symm
    _ = secondAddress.counterState := congrArg SearchAddress.counterState heq
    _ = second.1 := counterState_eq_of_mem_ruleAddresses hsecond

/-- Search addresses are unique within either oriented copy. -/
theorem rawCommandsFor_addresses_nodup (growth : Turing.Dir) :
    ((rawCommandsFor growth).map RawCommand.address).Nodup := by
  rw [rawCommandsFor_addresses, List.nodup_flatMap]
  constructor
  · intro rule _
    exact ruleAddresses_nodup growth rule
  · have hsource := GlobalSourceProgram.program_deterministic
    change (GlobalSourceProgram.program.map Prod.fst).Nodup at hsource
    rw [List.nodup_iff_pairwise_ne, List.pairwise_map] at hsource
    exact hsource.imp fun hne =>
      ruleAddresses_disjoint_of_source_ne growth hne

theorem address_counterState_of_mem_rawCommandsFor
    {growth : Turing.Dir} {command : RawCommand}
    (hcommand : command ∈ rawCommandsFor growth) :
    command.address.counterState ∈
      CounterMachine.sourceStates GlobalSourceProgram.program := by
  have haddress : command.address ∈
      (rawCommandsFor growth).map RawCommand.address :=
    List.mem_map.mpr ⟨command, hcommand, rfl⟩
  rw [rawCommandsFor_addresses] at haddress
  rcases List.mem_flatMap.mp haddress with ⟨rule, hrule, haddress⟩
  have hsource : rule.1 ∈
      CounterMachine.sourceStates GlobalSourceProgram.program :=
    List.mem_map.mpr ⟨rule, hrule, rfl⟩
  rw [counterState_eq_of_mem_ruleAddresses haddress]
  exact hsource

theorem address_growth_of_mem_rawCommandsFor
    {growth : Turing.Dir} {command : RawCommand}
    (hcommand : command ∈ rawCommandsFor growth) :
    command.address.growth = growth := by
  have haddress : command.address ∈
      (rawCommandsFor growth).map RawCommand.address :=
    List.mem_map.mpr ⟨command, hcommand, rfl⟩
  rw [rawCommandsFor_addresses] at haddress
  rcases List.mem_flatMap.mp haddress with ⟨rule, -, haddress⟩
  exact growth_eq_of_mem_ruleAddresses haddress

theorem address_slot_lt_of_mem_rawCommandsFor
    {growth : Turing.Dir} {command : RawCommand}
    (hcommand : command ∈ rawCommandsFor growth) :
    command.address.slot < directStride := by
  have haddress : command.address ∈
      (rawCommandsFor growth).map RawCommand.address :=
    List.mem_map.mpr ⟨command, hcommand, rfl⟩
  rw [rawCommandsFor_addresses] at haddress
  rcases List.mem_flatMap.mp haddress with ⟨rule, -, haddress⟩
  exact slot_lt_directStride_of_mem_ruleAddresses haddress

/-- The two copies also have disjoint search addresses because their
orientation field differs. -/
theorem rawCommands_orientations_disjoint :
    List.Disjoint
      ((rawCommandsFor .right).map RawCommand.address)
      ((rawCommandsFor .left).map RawCommand.address) := by
  rw [List.disjoint_iff_ne]
  intro rightAddress hright leftAddress hleft heq
  rcases List.mem_map.mp hright with ⟨rightCommand, hrightCommand, rfl⟩
  rcases List.mem_map.mp hleft with ⟨leftCommand, hleftCommand, rfl⟩
  have hrightGrowth := address_growth_of_mem_rawCommandsFor hrightCommand
  have hleftGrowth := address_growth_of_mem_rawCommandsFor hleftCommand
  have hgrowth := congrArg SearchAddress.growth heq
  simp_all

/-- Every generated bounded search has a unique symbolic address. -/
theorem rawCommandAddresses_nodup :
    (rawCommands.map RawCommand.address).Nodup := by
  rw [rawCommands, List.map_append]
  exact List.Nodup.append
    (rawCommandsFor_addresses_nodup .right)
    (rawCommandsFor_addresses_nodup .left)
    rawCommands_orientations_disjoint

/-- Every concrete raw command contributes its address to the global address
enumeration. -/
theorem rawCommand_address_mem {command : RawCommand}
    (hcommand : command ∈ rawCommands) :
    command.address ∈ rawCommands.map RawCommand.address :=
  List.mem_map.mpr ⟨command, hcommand, rfl⟩

theorem rawCommand_counterState_lt_logicalSpan {command : RawCommand}
    (hcommand : command ∈ rawCommands) :
    command.address.counterState < logicalSpan := by
  rw [rawCommands, List.mem_append] at hcommand
  rcases hcommand with hright | hleft
  · have hsource := address_counterState_of_mem_rawCommandsFor hright
    rcases List.mem_map.mp hsource with ⟨rule, hrule, hstate⟩
    rw [← hstate]
    exact state_lt_logicalSpan
      (CounterControlPlan.source_mem_programStates rule hrule)
  · have hsource := address_counterState_of_mem_rawCommandsFor hleft
    rcases List.mem_map.mp hsource with ⟨rule, hrule, hstate⟩
    rw [← hstate]
    exact state_lt_logicalSpan
      (CounterControlPlan.source_mem_programStates rule hrule)

theorem rawCommand_slot_lt_directStride {command : RawCommand}
    (hcommand : command ∈ rawCommands) :
    command.address.slot < directStride := by
  rw [rawCommands, List.mem_append] at hcommand
  exact hcommand.elim address_slot_lt_of_mem_rawCommandsFor
    address_slot_lt_of_mem_rawCommandsFor

/-! ## Exact executable search lookup -/

/-- Looking up the address stored at an enumeration index returns that exact
index; no later command aliases an earlier command block. -/
theorem searchIndex_get (tag : Fin rawCommands.length) :
    searchIndex (rawCommands.get tag).address = tag.val := by
  unfold searchIndex
  change List.idxOf (rawCommands.get tag).address
      (rawCommands.map RawCommand.address) = tag.val
  simpa [List.get_eq_getElem] using
    rawCommandAddresses_nodup.idxOf_getElem tag.val
      (by simp only [List.length_map]; exact tag.isLt)

@[simp]
theorem searchState_get (base : Nat) (c : Nat.Partrec.Code)
    (tag : Fin rawCommands.length) :
    searchState base c (rawCommands.get tag).address =
      commandOffset base (CanonicalInitializer.radius c) tag.val := by
  unfold searchState
  apply congrArg (commandOffset base (CanonicalInitializer.radius c))
  exact searchIndex_get tag

/-! ## Linking enumeration indices to bounded-command blocks -/

/-- Local copy of the generic list-index linker, kept here so this
well-formedness layer depends only on the construction module. -/
private theorem commandAt_get {numTags radius base : Nat}
    (commandList : List (Command numTags))
    (index : Fin commandList.length) :
    CommandAt radius base (commandOffset base radius index.val)
      (commandList.get index) commandList := by
  induction commandList generalizing base with
  | nil => exact Fin.elim0 index
  | cons first rest ih =>
      refine Fin.cases ?_ (fun tailIndex => ?_) index
      · simpa [commandOffset] using
          (CommandAt.head (radius := radius) base first rest)
      · have htail := ih (base := base + blockWidth radius) tailIndex
        simpa [commandOffset, Nat.succ_mul, Nat.add_assoc, Nat.add_comm,
          Nat.add_left_comm] using
          (CommandAt.tail (radius := radius) (offset := base)
            (commandOffset := commandOffset
              (base + blockWidth radius) radius tailIndex.val)
            (first := first) (command := rest.get tailIndex)
            (commands := rest) htail)

/-- The `tag`th compiled command is definitionally the command compiled with
that physical return tag. -/
theorem commands_get_eq_compileCommand (base : Nat) (c : Nat.Partrec.Code)
    (tag : Fin rawCommands.length) :
    (commands base c).get
        ⟨tag.val, by simpa only [commands_length, numTags] using tag.isLt⟩ =
      compileCommand base c tag := by
  change (List.ofFn (compileCommand base c)).get _ = _
  rw [List.get_ofFn]
  apply congrArg (compileCommand base c)
  apply Fin.ext
  rfl

/-- The command selected by a raw enumeration tag occupies exactly the
controller block denoted by its symbolic `searchState`. -/
theorem compileCommand_commandAt (base : Nat) (c : Nat.Partrec.Code)
    (tag : Fin rawCommands.length) :
    CommandAt (CanonicalInitializer.radius c) base
      (searchState base c (rawCommands.get tag).address)
      (compileCommand base c tag) (commands base c) := by
  let compiledTag : Fin (commands base c).length :=
    ⟨tag.val, by simpa only [commands_length, numTags] using tag.isLt⟩
  have hat := commandAt_get (radius := CanonicalInitializer.radius c)
    (base := base) (commands base c) compiledTag
  rw [searchState_get]
  rw [show (commands base c).get compiledTag = compileCommand base c tag by
    exact commands_get_eq_compileCommand base c tag] at hat
  exact hat

/-- Equivalent form retaining the actual `List.get` expression used by
downstream enumeration arguments. -/
theorem commands_get_commandAt (base : Nat) (c : Nat.Partrec.Code)
    (tag : Fin rawCommands.length) :
    CommandAt (CanonicalInitializer.radius c) base
      (searchState base c (rawCommands.get tag).address)
      ((commands base c).get
        ⟨tag.val, by simpa only [commands_length, numTags] using tag.isLt⟩)
      (commands base c) := by
  rw [commands_get_eq_compileCommand]
  exact compileCommand_commandAt base c tag

/-- Namespace-form alias for downstream controller semantics. -/
theorem CommandAt.compileCommand (base : Nat) (c : Nat.Partrec.Code)
    (tag : Fin rawCommands.length) :
    CommandAt (CanonicalInitializer.radius c) base
      (searchState base c (rawCommands.get tag).address)
      (compileCommand base c tag) (commands base c) :=
  compileCommand_commandAt base c tag

end

end CounterControlWellFormed
end Hooper
end Kari
end LeanWang
