/-
Copyright (c) 2026 lean-wang contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Erik Demaine, Stefan Langerman, GPT 5.5
-/
import LeanWang.Kari.Hooper.MarkerMachine

/-!
# Relocatable finite TM0 programs

The state names generated by `FiniteTM0` are natural numbers.  This module
turns that choice into a small linker: a finite table can be relocated into a
fresh state interval, and every full-tape execution of the original table
lifts to the relocated table without changing the tape.

The final theorem packages `MarkerMachine.moveMarker_reaches` as a block with
entry state `offset` and exit state `offset + 3`.  It is the semantic primitive
used when assembling all suffix-marker moves for a counter instruction.
-/

namespace LeanWang
namespace Kari
namespace Hooper
namespace FiniteTM0Program

open Turing

variable {numSymbols : Nat}

/-- Add an offset to the control state returned by a rule lookup. -/
def relocateResult (offset : FiniteTM0.State)
    (result : FiniteTM0.Result numSymbols) :
    FiniteTM0.Result numSymbols :=
  (offset + result.1, result.2)

/-- Add an offset to both control states of one explicit finite rule. -/
def relocateRule (offset : FiniteTM0.State)
    (rule : FiniteTM0.Rule numSymbols) : FiniteTM0.Rule numSymbols :=
  FiniteTM0.Rule.mk (offset + rule.1.1) rule.1.2
    (offset + rule.2.1) rule.2.2

/-- Relocate a whole table into the state interval beginning at `offset`. -/
def relocate (offset : FiniteTM0.State)
    (rules : FiniteTM0.Table numSymbols) : FiniteTM0.Table numSymbols :=
  rules.map (relocateRule offset)

/-- Relocating one explicit finite rule is primitive recursive. -/
theorem relocateRule_primrec :
    Primrec fun input : FiniteTM0.State × FiniteTM0.Rule numSymbols =>
      relocateRule input.1 input.2 := by
  have hoffset : Primrec fun input :
      FiniteTM0.State × FiniteTM0.Rule numSymbols => input.1 :=
    Primrec.fst
  have hsource : Primrec fun input :
      FiniteTM0.State × FiniteTM0.Rule numSymbols => input.2.1.1 :=
    Primrec.fst.comp (Primrec.fst.comp Primrec.snd)
  have hread : Primrec fun input :
      FiniteTM0.State × FiniteTM0.Rule numSymbols => input.2.1.2 :=
    Primrec.snd.comp (Primrec.fst.comp Primrec.snd)
  have htarget : Primrec fun input :
      FiniteTM0.State × FiniteTM0.Rule numSymbols => input.2.2.1 :=
    Primrec.fst.comp (Primrec.snd.comp Primrec.snd)
  have haction : Primrec fun input :
      FiniteTM0.State × FiniteTM0.Rule numSymbols => input.2.2.2 :=
    Primrec.snd.comp (Primrec.snd.comp Primrec.snd)
  exact Primrec.pair
    (Primrec.pair (Primrec.nat_add.comp hoffset hsource) hread)
    (Primrec.pair (Primrec.nat_add.comp hoffset htarget) haction)

/-- Relocating a finite rule table is primitive recursive. -/
theorem relocate_primrec :
    Primrec fun input : FiniteTM0.State × FiniteTM0.Table numSymbols =>
      relocate input.1 input.2 := by
  have hrule : Primrec₂ fun input :
      FiniteTM0.State × FiniteTM0.Table numSymbols =>
      fun rule : FiniteTM0.Rule numSymbols => relocateRule input.1 rule :=
    (Primrec.to₂ relocateRule_primrec).comp₂
      (Primrec.fst.comp₂ Primrec₂.left) Primrec₂.right
  exact Primrec.list_map Primrec.snd hrule

/-- Computability corollary for the finite-table linker. -/
theorem relocate_computable :
    Computable fun input : FiniteTM0.State × FiniteTM0.Table numSymbols =>
      relocate input.1 input.2 :=
  relocate_primrec.to_comp

@[simp]
theorem relocate_nil (offset : FiniteTM0.State) :
    relocate offset ([] : FiniteTM0.Table numSymbols) = [] :=
  rfl

@[simp]
theorem relocate_cons (offset : FiniteTM0.State)
    (rule : FiniteTM0.Rule numSymbols) (rules : FiniteTM0.Table numSymbols) :
    relocate offset (rule :: rules) =
      relocateRule offset rule :: relocate offset rules :=
  rfl

/-- Lookup commutes with relocation when the queried state is relocated by
the same offset. -/
theorem lookupAction_relocate (offset q : FiniteTM0.State)
    (a : FiniteTM0.Symbol numSymbols)
    (rules : FiniteTM0.Table numSymbols) :
    FiniteTM0.lookupAction (relocate offset rules) (offset + q) a =
      (FiniteTM0.lookupAction rules q a).map (relocateResult offset) := by
  induction rules with
  | nil => rfl
  | cons rule rules ih =>
      rcases rule with ⟨⟨source, read⟩, ⟨target, action⟩⟩
      by_cases hkey : (q, a) = (source, read)
      · rcases hkey with ⟨rfl, rfl⟩
        simp [relocate, relocateRule, relocateResult,
          FiniteTM0.lookupAction]
      · have hrelocated :
        (offset + q, a) ≠ (offset + source, read) := by
          intro h
          rcases Prod.mk.inj h with ⟨hstate, hsymbol⟩
          apply hkey
          apply Prod.ext
          · exact Nat.add_left_cancel hstate
          · exact hsymbol
        change FiniteTM0.lookupAction
            (FiniteTM0.Rule.mk (offset + source) read (offset + target) action ::
              relocate offset rules) (offset + q) a =
          (FiniteTM0.lookupAction
            (FiniteTM0.Rule.mk source read target action :: rules) q a).map
              (relocateResult offset)
        rw [FiniteTM0.lookupAction_cons_ne hrelocated]
        rw [FiniteTM0.lookupAction_cons_ne hkey]
        exact ih

/-- Relocate only the control state of a full-tape configuration. -/
def liftCfg (offset : FiniteTM0.State)
    (cfg : FullTM0.Cfg (FiniteTM0.Symbol numSymbols) FiniteTM0.State) :
    FullTM0.Cfg (FiniteTM0.Symbol numSymbols) FiniteTM0.State :=
  ⟨offset + cfg.q, cfg.tape⟩

@[simp]
theorem liftCfg_q (offset : FiniteTM0.State)
    (cfg : FullTM0.Cfg (FiniteTM0.Symbol numSymbols) FiniteTM0.State) :
    (liftCfg offset cfg).q = offset + cfg.q :=
  rfl

@[simp]
theorem liftCfg_tape (offset : FiniteTM0.State)
    (cfg : FullTM0.Cfg (FiniteTM0.Symbol numSymbols) FiniteTM0.State) :
    (liftCfg offset cfg).tape = cfg.tape :=
  rfl

/-- A single semantic step of a table commutes with state relocation. -/
theorem step_relocate (offset : FiniteTM0.State)
    (rules : FiniteTM0.Table numSymbols)
    (cfg : FullTM0.Cfg (FiniteTM0.Symbol numSymbols) FiniteTM0.State) :
    FullTM0.step (FiniteTM0.machine (relocate offset rules))
        (liftCfg offset cfg) =
      (FullTM0.step (FiniteTM0.machine rules) cfg).map (liftCfg offset) := by
  simp only [FullTM0.step, FiniteTM0.machine, FullTM0.Tape.read_eq,
    liftCfg_q, liftCfg_tape]
  rw [lookupAction_relocate]
  cases hlookup : FiniteTM0.lookupAction rules cfg.q (cfg.tape 0) with
  | none => simp
  | some result =>
      rcases result with ⟨target, action⟩
      cases action <;> rfl

/-- Every finite execution path lifts to a relocated copy of the table. -/
theorem reaches_relocate (offset : FiniteTM0.State)
    (rules : FiniteTM0.Table numSymbols)
    {start finish :
      FullTM0.Cfg (FiniteTM0.Symbol numSymbols) FiniteTM0.State}
    (hreach : FullTM0.Reaches (FiniteTM0.machine rules) start finish) :
    FullTM0.Reaches (FiniteTM0.machine (relocate offset rules))
      (liftCfg offset start) (liftCfg offset finish) := by
  induction hreach with
  | refl => exact Relation.ReflTransGen.refl
  | tail hpath hstep ih =>
      apply Relation.ReflTransGen.tail ih
      rw [step_relocate]
      simpa using Option.mem_map_of_mem (liftCfg offset) hstep

/-! ## Linking tables by concatenation -/

/-- Association-list lookup in a concatenation first consults the first
table and consults the second exactly when the first has no rule. -/
theorem lookupAction_append (first second : FiniteTM0.Table numSymbols)
    (q : FiniteTM0.State) (a : FiniteTM0.Symbol numSymbols) :
    FiniteTM0.lookupAction (first ++ second) q a =
      match FiniteTM0.lookupAction first q a with
      | some result => some result
      | none => FiniteTM0.lookupAction second q a := by
  induction first with
  | nil => rfl
  | cons rule first ih =>
      rcases rule with ⟨key, result⟩
      by_cases hkey : (q, a) = key
      · simp [FiniteTM0.lookupAction, hkey]
      · simp [FiniteTM0.lookupAction, hkey, ih]

/-- Adding rules after a table cannot change a step that the first table
already defines. -/
theorem step_append_of_ne_none
    (first second : FiniteTM0.Table numSymbols)
    (cfg : FullTM0.Cfg (FiniteTM0.Symbol numSymbols) FiniteTM0.State)
    (hdefined : FullTM0.step (FiniteTM0.machine first) cfg ≠ none) :
    FullTM0.step (FiniteTM0.machine (first ++ second)) cfg =
      FullTM0.step (FiniteTM0.machine first) cfg := by
  simp only [FullTM0.step, FiniteTM0.machine, FullTM0.Tape.read_eq]
  rw [lookupAction_append]
  cases hlookup : FiniteTM0.lookupAction first cfg.q (cfg.tape 0) with
  | none =>
      exfalso
      apply hdefined
      simp [FullTM0.step, FiniteTM0.machine, hlookup]
  | some result => simp

/-- Every finite path through the first table remains a path after appending
an arbitrary second table. -/
theorem reaches_append_left
    (first second : FiniteTM0.Table numSymbols)
    {start finish :
      FullTM0.Cfg (FiniteTM0.Symbol numSymbols) FiniteTM0.State}
    (hreach : FullTM0.Reaches (FiniteTM0.machine first) start finish) :
    FullTM0.Reaches (FiniteTM0.machine (first ++ second)) start finish := by
  apply Relation.ReflTransGen.mono ?_ hreach
  intro current next hstep
  have hdefined :
      FullTM0.step (FiniteTM0.machine first) current ≠ none := by
    intro hnone
    rw [hnone] at hstep
    simp at hstep
  rw [step_append_of_ne_none first second current hdefined]
  exact hstep

/-! ## Relocating the concrete marker-move primitive -/

/-- The four-rule marker primitive placed at an arbitrary fresh offset.  It
owns source states `offset`, `offset+1`, and `offset+2`; `offset+3` is its
fall-through exit. -/
def moveMarkerTable (offset : FiniteTM0.State) (expected : Fin 5)
    (direction : Turing.Dir) :
    FiniteTM0.Table MarkerMachine.AlphabetSize :=
  relocate offset (MarkerMachine.program expected direction)

/-- Exact reachability theorem for a relocated marker-move block. -/
theorem moveMarker_reaches (offset : FiniteTM0.State)
    (expected : Fin 5) (direction : Turing.Dir)
    (T : FullTM0.Tape MarkerMachine.Symbol) (distance : Nat)
    (hgap : SearchGap (fun a => a = MarkerMachine.blankSymbol)
      (fun a => a = MarkerMachine.boundarySymbol expected)
      T direction distance)
    (hdestination :
      (((T.moveN direction distance).write MarkerMachine.blankSymbol).move
          direction).read = MarkerMachine.blankSymbol) :
    FullTM0.Reaches (FiniteTM0.machine
        (moveMarkerTable offset expected direction))
      ⟨offset, T⟩
      ⟨offset + 3,
        (((T.moveN direction distance).write MarkerMachine.blankSymbol).move
          direction).write (MarkerMachine.boundarySymbol expected)⟩ := by
  have h := reaches_relocate offset
    (MarkerMachine.program expected direction)
    (MarkerMachine.moveMarker_reaches expected direction T distance
      hgap hdestination)
  simpa [moveMarkerTable, liftCfg, MarkerMachine.searchState,
    MarkerMachine.doneState] using h

end FiniteTM0Program
end Hooper
end Kari
end LeanWang
